name: Rust

on:
  push:
    branches: ["dev"]

jobs:
  deploy:
    permissions:
      pages: write
      contents: write
      id-token: write
    #
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Configuration
        run: rustup update nightly && rustup default nightly
      - name: Rust Target Add
        run: rustup target add wasm32-unknown-unknown
      - name: Trunk Download
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build
        run: ./trunk build --release
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
